// <auto-generated>
//     Generated by tools/gen-strings.py from Strings.resx. Do not edit by hand: edit the script,
//     run it, and commit both. A parity test asserts this file and the three resx agree.
// </auto-generated>

using System.Globalization;
using System.Resources;

namespace AppLedger.App.Resources;

/// <summary>Every user-visible string in the UI (docs/14_I18N.md).</summary>
/// <remarks>
/// <b>Public, and it has to be.</b> XAML's <c>{x:Static}</c> resolves through public reflection, so an
/// internal class compiles cleanly and then throws at window construction - "StaticExtension value
/// cannot be resolved to an enumeration, static field, or static property". Only running it says so.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("tools/gen-strings.py", "1.0")]
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("AppLedger.App.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Looks a key up in the current UI culture.</summary>
    public static string Get(string key) =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    /// <summary>AppLedger</summary>
    public static string App_Title => Get(nameof(App_Title));

    /// <summary>Home</summary>
    public static string Nav_Home => Get(nameof(Nav_Home));

    /// <summary>Apps</summary>
    public static string Nav_Apps => Get(nameof(Nav_Apps));

    /// <summary>Installed</summary>
    public static string Nav_Installed => Get(nameof(Nav_Installed));

    /// <summary>Alerts</summary>
    public static string Nav_Alerts => Get(nameof(Nav_Alerts));

    /// <summary>Settings</summary>
    public static string Nav_Settings => Get(nameof(Nav_Settings));

    /// <summary>Home</summary>
    public static string Page_Home_Title => Get(nameof(Page_Home_Title));

    /// <summary>Running apps</summary>
    public static string Page_Apps_Title => Get(nameof(Page_Apps_Title));

    /// <summary>Installed apps</summary>
    public static string Page_Installed_Title => Get(nameof(Page_Installed_Title));

    /// <summary>Alerts</summary>
    public static string Page_Alerts_Title => Get(nameof(Page_Alerts_Title));

    /// <summary>Settings</summary>
    public static string Page_Settings_Title => Get(nameof(Page_Settings_Title));

    /// <summary>This page arrives in a later milestone.</summary>
    public static string State_NotYetBuilt => Get(nameof(State_NotYetBuilt));

    /// <summary>No data yet. The Agent has only just started collecting.</summary>
    public static string State_NoDataYet => Get(nameof(State_NoDataYet));

    /// <summary>_File</summary>
    public static string Menu_File => Get(nameof(Menu_File));

    /// <summary>E_xit</summary>
    public static string Menu_File_Exit => Get(nameof(Menu_File_Exit));

    /// <summary>_View</summary>
    public static string Menu_View => Get(nameof(Menu_View));

    /// <summary>_Help</summary>
    public static string Menu_Help => Get(nameof(Menu_Help));

    /// <summary>_About</summary>
    public static string Menu_Help_About => Get(nameof(Menu_Help_About));

    /// <summary>Every key this class exposes, for the parity test.</summary>
    public static IReadOnlyList<string> Keys { get; } =
    [
        nameof(App_Title),
        nameof(Nav_Home),
        nameof(Nav_Apps),
        nameof(Nav_Installed),
        nameof(Nav_Alerts),
        nameof(Nav_Settings),
        nameof(Page_Home_Title),
        nameof(Page_Apps_Title),
        nameof(Page_Installed_Title),
        nameof(Page_Alerts_Title),
        nameof(Page_Settings_Title),
        nameof(State_NotYetBuilt),
        nameof(State_NoDataYet),
        nameof(Menu_File),
        nameof(Menu_File_Exit),
        nameof(Menu_View),
        nameof(Menu_Help),
        nameof(Menu_Help_About),
    ];
}
