// <auto-generated>
//     Generated by tools/gen-strings.py from Strings.resx. Do not edit by hand: edit the script,
//     run it, and commit both. A parity test asserts this file and the three resx agree.
// </auto-generated>

using System.Globalization;
using System.Resources;

namespace AppLedger.App.Resources;

/// <summary>Every user-visible string in the UI (docs/14_I18N.md).</summary>
/// <remarks>
/// <b>Public, and it has to be.</b> XAML's <c>{x:Static}</c> resolves through public reflection, so an
/// internal class compiles cleanly and then throws at window construction - "StaticExtension value
/// cannot be resolved to an enumeration, static field, or static property". Only running it says so.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("tools/gen-strings.py", "1.0")]
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("AppLedger.App.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Looks a key up in the current UI culture.</summary>
    public static string Get(string key) =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    /// <summary>AppLedger</summary>
    public static string App_Title => Get(nameof(App_Title));

    /// <summary>Home</summary>
    public static string Nav_Home => Get(nameof(Nav_Home));

    /// <summary>Apps</summary>
    public static string Nav_Apps => Get(nameof(Nav_Apps));

    /// <summary>Installed</summary>
    public static string Nav_Installed => Get(nameof(Nav_Installed));

    /// <summary>Alerts</summary>
    public static string Nav_Alerts => Get(nameof(Nav_Alerts));

    /// <summary>Settings</summary>
    public static string Nav_Settings => Get(nameof(Nav_Settings));

    /// <summary>Home</summary>
    public static string Page_Home_Title => Get(nameof(Page_Home_Title));

    /// <summary>Running apps</summary>
    public static string Page_Apps_Title => Get(nameof(Page_Apps_Title));

    /// <summary>Installed apps</summary>
    public static string Page_Installed_Title => Get(nameof(Page_Installed_Title));

    /// <summary>Alerts</summary>
    public static string Page_Alerts_Title => Get(nameof(Page_Alerts_Title));

    /// <summary>Settings</summary>
    public static string Page_Settings_Title => Get(nameof(Page_Settings_Title));

    /// <summary>This page arrives in a later milestone.</summary>
    public static string State_NotYetBuilt => Get(nameof(State_NotYetBuilt));

    /// <summary>No data yet. The Agent has only just started collecting.</summary>
    public static string State_NoDataYet => Get(nameof(State_NoDataYet));

    /// <summary>Step {0} of {1}</summary>
    public static string Onboarding_Step => Get(nameof(Onboarding_Step));

    /// <summary>Continue</summary>
    public static string Onboarding_Continue => Get(nameof(Onboarding_Continue));

    /// <summary>Back</summary>
    public static string Onboarding_Back => Get(nameof(Onboarding_Back));

    /// <summary>Before we start</summary>
    public static string Privacy_Gate_Title => Get(nameof(Privacy_Gate_Title));

    /// <summary>What is recorded</summary>
    public static string Privacy_Gate_What_Heading => Get(nameof(Privacy_Gate_What_Heading));

    /// <summary>AppLedger records which apps run, how much CPU/memory/disk/network they use, where they store files, and - for most apps - which websites/hosts they talk to.</summary>
    public static string Privacy_Gate_What_Body => Get(nameof(Privacy_Gate_What_Body));

    /// <summary>Web browsers</summary>
    public static string Privacy_Gate_Browsers_Heading => Get(nameof(Privacy_Gate_Browsers_Heading));

    /// <summary>For web browsers we record only how much data they used, not which sites. You can change this per app.</summary>
    public static string Privacy_Gate_Browsers_Body => Get(nameof(Privacy_Gate_Browsers_Body));

    /// <summary>Where it is stored</summary>
    public static string Privacy_Gate_Where_Heading => Get(nameof(Privacy_Gate_Where_Heading));

    /// <summary>Everything stays on this PC in %LOCALAPPDATA%\AppLedgerData. Nothing is uploaded. AppLedger has no accounts.</summary>
    public static string Privacy_Gate_Where_Body => Get(nameof(Privacy_Gate_Where_Body));

    /// <summary>How long it is kept</summary>
    public static string Privacy_Gate_HowLong_Heading => Get(nameof(Privacy_Gate_HowLong_Heading));

    /// <summary>6 months by default. You can shorten it, pause, or delete everything in one click.</summary>
    public static string Privacy_Gate_HowLong_Body => Get(nameof(Privacy_Gate_HowLong_Body));

    /// <summary>Who can see it</summary>
    public static string Privacy_Gate_Who_Heading => Get(nameof(Privacy_Gate_Who_Heading));

    /// <summary>Anyone who can log in as you on this PC. Protect your account accordingly.</summary>
    public static string Privacy_Gate_Who_Body => Get(nameof(Privacy_Gate_Who_Body));

    /// <summary>Read full policy</summary>
    public static string Privacy_Gate_ReadPolicy => Get(nameof(Privacy_Gate_ReadPolicy));

    /// <summary>The background Agent</summary>
    public static string Agent_Setup_Title => Get(nameof(Agent_Setup_Title));

    /// <summary>Network, disk and DNS figures need a small background service that runs with administrator rights and starts when you sign in. Installing it asks for permission once.</summary>
    public static string Agent_Setup_Body => Get(nameof(Agent_Setup_Body));

    /// <summary>It stays under 1% CPU when idle and under 100 MB of memory.</summary>
    public static string Agent_Setup_Budget => Get(nameof(Agent_Setup_Budget));

    /// <summary>Install Agent</summary>
    public static string Agent_Setup_Install => Get(nameof(Agent_Setup_Install));

    /// <summary>Continue in Lite mode</summary>
    public static string Agent_Setup_Skip => Get(nameof(Agent_Setup_Skip));

    /// <summary>The Agent is installed and running.</summary>
    public static string Agent_Setup_Installed => Get(nameof(Agent_Setup_Installed));

    /// <summary>Continuing without the Agent. You can install it later from Settings.</summary>
    public static string Agent_Setup_Declined => Get(nameof(Agent_Setup_Declined));

    /// <summary>Start Agent</summary>
    public static string Agent_Start => Get(nameof(Agent_Start));

    /// <summary>Defaults</summary>
    public static string Defaults_Title => Get(nameof(Defaults_Title));

    /// <summary>Keep history for {0} days</summary>
    public static string Defaults_Retention => Get(nameof(Defaults_Retention));

    /// <summary>Done</summary>
    public static string Defaults_Done => Get(nameof(Defaults_Done));

    /// <summary>App</summary>
    public static string Col_App => Get(nameof(Col_App));

    /// <summary>Procs</summary>
    public static string Col_Procs => Get(nameof(Col_Procs));

    /// <summary>CPU %</summary>
    public static string Col_Cpu => Get(nameof(Col_Cpu));

    /// <summary>Memory</summary>
    public static string Col_Memory => Get(nameof(Col_Memory));

    /// <summary>GPU %</summary>
    public static string Col_Gpu => Get(nameof(Col_Gpu));

    /// <summary>Disk R</summary>
    public static string Col_DiskRead => Get(nameof(Col_DiskRead));

    /// <summary>Disk W</summary>
    public static string Col_DiskWrite => Get(nameof(Col_DiskWrite));

    /// <summary>Net down</summary>
    public static string Col_NetIn => Get(nameof(Col_NetIn));

    /// <summary>Net up</summary>
    public static string Col_NetOut => Get(nameof(Col_NetOut));

    /// <summary>Connecting</summary>
    public static string Health_Mode_Connecting => Get(nameof(Health_Mode_Connecting));

    /// <summary>Full</summary>
    public static string Health_Mode_Full => Get(nameof(Health_Mode_Full));

    /// <summary>Degraded</summary>
    public static string Health_Mode_Degraded => Get(nameof(Health_Mode_Degraded));

    /// <summary>Lite</summary>
    public static string Health_Mode_Lite => Get(nameof(Health_Mode_Lite));

    /// <summary>Agent CPU</summary>
    public static string Health_Cpu => Get(nameof(Health_Cpu));

    /// <summary>Agent memory</summary>
    public static string Health_Memory => Get(nameof(Health_Memory));

    /// <summary>Sensors</summary>
    public static string Health_Sensors => Get(nameof(Health_Sensors));

    /// <summary>Running without the Agent</summary>
    public static string Lite_Banner_Title => Get(nameof(Lite_Banner_Title));

    /// <summary>Network, disk and DNS figures need the background Agent, which runs with administrator rights. Everything shown here comes from what a standard user can see.</summary>
    public static string Lite_Banner_Body => Get(nameof(Lite_Banner_Body));

    /// <summary>N/A</summary>
    public static string Value_NotAvailable => Get(nameof(Value_NotAvailable));

    /// <summary>_File</summary>
    public static string Menu_File => Get(nameof(Menu_File));

    /// <summary>E_xit</summary>
    public static string Menu_File_Exit => Get(nameof(Menu_File_Exit));

    /// <summary>_View</summary>
    public static string Menu_View => Get(nameof(Menu_View));

    /// <summary>_Help</summary>
    public static string Menu_Help => Get(nameof(Menu_Help));

    /// <summary>_About</summary>
    public static string Menu_Help_About => Get(nameof(Menu_Help_About));

    /// <summary>Every key this class exposes, for the parity test.</summary>
    public static IReadOnlyList<string> Keys { get; } =
    [
        nameof(App_Title),
        nameof(Nav_Home),
        nameof(Nav_Apps),
        nameof(Nav_Installed),
        nameof(Nav_Alerts),
        nameof(Nav_Settings),
        nameof(Page_Home_Title),
        nameof(Page_Apps_Title),
        nameof(Page_Installed_Title),
        nameof(Page_Alerts_Title),
        nameof(Page_Settings_Title),
        nameof(State_NotYetBuilt),
        nameof(State_NoDataYet),
        nameof(Onboarding_Step),
        nameof(Onboarding_Continue),
        nameof(Onboarding_Back),
        nameof(Privacy_Gate_Title),
        nameof(Privacy_Gate_What_Heading),
        nameof(Privacy_Gate_What_Body),
        nameof(Privacy_Gate_Browsers_Heading),
        nameof(Privacy_Gate_Browsers_Body),
        nameof(Privacy_Gate_Where_Heading),
        nameof(Privacy_Gate_Where_Body),
        nameof(Privacy_Gate_HowLong_Heading),
        nameof(Privacy_Gate_HowLong_Body),
        nameof(Privacy_Gate_Who_Heading),
        nameof(Privacy_Gate_Who_Body),
        nameof(Privacy_Gate_ReadPolicy),
        nameof(Agent_Setup_Title),
        nameof(Agent_Setup_Body),
        nameof(Agent_Setup_Budget),
        nameof(Agent_Setup_Install),
        nameof(Agent_Setup_Skip),
        nameof(Agent_Setup_Installed),
        nameof(Agent_Setup_Declined),
        nameof(Agent_Start),
        nameof(Defaults_Title),
        nameof(Defaults_Retention),
        nameof(Defaults_Done),
        nameof(Col_App),
        nameof(Col_Procs),
        nameof(Col_Cpu),
        nameof(Col_Memory),
        nameof(Col_Gpu),
        nameof(Col_DiskRead),
        nameof(Col_DiskWrite),
        nameof(Col_NetIn),
        nameof(Col_NetOut),
        nameof(Health_Mode_Connecting),
        nameof(Health_Mode_Full),
        nameof(Health_Mode_Degraded),
        nameof(Health_Mode_Lite),
        nameof(Health_Cpu),
        nameof(Health_Memory),
        nameof(Health_Sensors),
        nameof(Lite_Banner_Title),
        nameof(Lite_Banner_Body),
        nameof(Value_NotAvailable),
        nameof(Menu_File),
        nameof(Menu_File_Exit),
        nameof(Menu_View),
        nameof(Menu_Help),
        nameof(Menu_Help_About),
    ];
}
